apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    kubernetes.digitalocean.com/load-balancer-id: "load-balancer-1"
    service.beta.kubernetes.io/do-loadbalancer-size-unit: "1"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
spec:
  type: LoadBalancer
  selector:
    app: microbrewers
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: web

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microbrewers-deployment
  labels:
    app: microbrewers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microbrewers
  template:
    metadata:
      labels:
        app: microbrewers
    spec:
      containers:
      - name: microbrewers
        image: registry.digitalocean.com/microbrewers/microbrewers:latest
        ports:
          - name: web
            protocol: TCP
            containerPort: 3000
        env:
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: database-url
                    key: DATABASE_URL
