---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microbrewers-api-deployment
  labels:
    app: microbrewers-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microbrewers-api-pod
  template:
    metadata:
      labels:
        app: microbrewers-api-pod
    spec:
      containers:
      - name: microbrewers-api
        image: fra.ocir.io/fr2tp465ruxb/microbrewers-staging:latest
        ports:
          - name: web
            protocol: "TCP"
            containerPort: 3000
        env:
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: database-url
                    key: DATABASE_URL
              - name: OCI_DATA_URL
                valueFrom:
                  secretKeyRef:
                    name: oci-data-url
                    key: OCI_DATA_URL
      imagePullSecrets:
        - name: microbrewers-image-registry
---
apiVersion: v1
kind: Service
metadata:
  name: microbrewers-api-service
  labels:
    app: microbrewers
spec:
   type: LoadBalancer
   ports:
     - protocol: TCP
       port: 3000
       targetPort: 3000
   selector:
     app: microbrewers-api-pod
