name: Continuous Integration
on: push
env:
  NODE_VERSION: "17.1.0"

jobs:
  yarn_stylelint:
    name: Yarn Stylelint
    runs-on: ubuntu-18.04

    steps:
      - name: checkout-repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run: export PATH="$HOME/.yarn/bin:$PATH"

      - run: yarn --frozen-lockfile
      - run: yarn stylelint

  yarn_eslint:
    name: Yarn Eslint
    runs-on: ubuntu-18.04

    steps:
      - name: checkout-repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run: export PATH="$HOME/.yarn/bin:$PATH"

      - run: yarn --frozen-lockfile
      - run: yarn eslint --max-warnings=0

  zeitwerk:
    name: Zeitwerk
    runs-on: ubuntu-18.04

    steps:
      - name: checkout-repo
        uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - run: gem install bundler --no-document
      - run: bundle install --without development test
      - run: export $(grep -v '^#' .env.build | xargs) && bin/rails zeitwerk:check

  brakeman:
    name: Brakeman
    runs-on: ubuntu-18.04

    steps:
      - name: checkout-repo
        uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1

      - run: gem install brakeman
      - run: brakeman --run-all-checks --interprocedural --no-pager --exit-on-warn --exit-on-error --add-libs-path app

  ruby_audit:
    name: Ruby Audit
    runs-on: ubuntu-18.04

    steps:
      - name: checkout-repo
        uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1

      - run: gem install ruby_audit
      - run: bin/ruby-audit

  bundle_audit:
    name: Bundle Audit
    runs-on: ubuntu-18.04

    steps:
      - name: checkout-repo
        uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - run: gem install bundler-audit
      - run: bundle audit check --update

  rufo-and-rubocop:
    name: Rufo and Rubocop
    runs-on: ubuntu-18.04

    steps:
      - name: checkout-repo
        uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1

      - run: gem install bundle-only
      - run: bundle-only linting
      - run: rubocop -P
